/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	cephrookiov1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCephObjectStoreZones implements CephObjectStoreZoneInterface
type FakeCephObjectStoreZones struct {
	Fake *FakeCephV1
	ns   string
}

var cephobjectstorezonesResource = schema.GroupVersionResource{Group: "ceph.rook.io", Version: "v1", Resource: "cephobjectstorezones"}

var cephobjectstorezonesKind = schema.GroupVersionKind{Group: "ceph.rook.io", Version: "v1", Kind: "CephObjectStoreZone"}

// Get takes name of the cephObjectStoreZone, and returns the corresponding cephObjectStoreZone object, and an error if there is any.
func (c *FakeCephObjectStoreZones) Get(name string, options v1.GetOptions) (result *cephrookiov1.CephObjectStoreZone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cephobjectstorezonesResource, c.ns, name), &cephrookiov1.CephObjectStoreZone{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreZone), err
}

// List takes label and field selectors, and returns the list of CephObjectStoreZones that match those selectors.
func (c *FakeCephObjectStoreZones) List(opts v1.ListOptions) (result *cephrookiov1.CephObjectStoreZoneList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cephobjectstorezonesResource, cephobjectstorezonesKind, c.ns, opts), &cephrookiov1.CephObjectStoreZoneList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cephrookiov1.CephObjectStoreZoneList{ListMeta: obj.(*cephrookiov1.CephObjectStoreZoneList).ListMeta}
	for _, item := range obj.(*cephrookiov1.CephObjectStoreZoneList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cephObjectStoreZones.
func (c *FakeCephObjectStoreZones) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cephobjectstorezonesResource, c.ns, opts))

}

// Create takes the representation of a cephObjectStoreZone and creates it.  Returns the server's representation of the cephObjectStoreZone, and an error, if there is any.
func (c *FakeCephObjectStoreZones) Create(cephObjectStoreZone *cephrookiov1.CephObjectStoreZone) (result *cephrookiov1.CephObjectStoreZone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cephobjectstorezonesResource, c.ns, cephObjectStoreZone), &cephrookiov1.CephObjectStoreZone{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreZone), err
}

// Update takes the representation of a cephObjectStoreZone and updates it. Returns the server's representation of the cephObjectStoreZone, and an error, if there is any.
func (c *FakeCephObjectStoreZones) Update(cephObjectStoreZone *cephrookiov1.CephObjectStoreZone) (result *cephrookiov1.CephObjectStoreZone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cephobjectstorezonesResource, c.ns, cephObjectStoreZone), &cephrookiov1.CephObjectStoreZone{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreZone), err
}

// Delete takes name of the cephObjectStoreZone and deletes it. Returns an error if one occurs.
func (c *FakeCephObjectStoreZones) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cephobjectstorezonesResource, c.ns, name), &cephrookiov1.CephObjectStoreZone{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCephObjectStoreZones) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cephobjectstorezonesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &cephrookiov1.CephObjectStoreZoneList{})
	return err
}

// Patch applies the patch and returns the patched cephObjectStoreZone.
func (c *FakeCephObjectStoreZones) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cephrookiov1.CephObjectStoreZone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cephobjectstorezonesResource, c.ns, name, pt, data, subresources...), &cephrookiov1.CephObjectStoreZone{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreZone), err
}
