/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	cephrookiov1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCephObjectStoreRealms implements CephObjectStoreRealmInterface
type FakeCephObjectStoreRealms struct {
	Fake *FakeCephV1
	ns   string
}

var cephobjectstorerealmsResource = schema.GroupVersionResource{Group: "ceph.rook.io", Version: "v1", Resource: "cephobjectstorerealms"}

var cephobjectstorerealmsKind = schema.GroupVersionKind{Group: "ceph.rook.io", Version: "v1", Kind: "CephObjectStoreRealm"}

// Get takes name of the cephObjectStoreRealm, and returns the corresponding cephObjectStoreRealm object, and an error if there is any.
func (c *FakeCephObjectStoreRealms) Get(name string, options v1.GetOptions) (result *cephrookiov1.CephObjectStoreRealm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cephobjectstorerealmsResource, c.ns, name), &cephrookiov1.CephObjectStoreRealm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreRealm), err
}

// List takes label and field selectors, and returns the list of CephObjectStoreRealms that match those selectors.
func (c *FakeCephObjectStoreRealms) List(opts v1.ListOptions) (result *cephrookiov1.CephObjectStoreRealmList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cephobjectstorerealmsResource, cephobjectstorerealmsKind, c.ns, opts), &cephrookiov1.CephObjectStoreRealmList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cephrookiov1.CephObjectStoreRealmList{ListMeta: obj.(*cephrookiov1.CephObjectStoreRealmList).ListMeta}
	for _, item := range obj.(*cephrookiov1.CephObjectStoreRealmList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cephObjectStoreRealms.
func (c *FakeCephObjectStoreRealms) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cephobjectstorerealmsResource, c.ns, opts))

}

// Create takes the representation of a cephObjectStoreRealm and creates it.  Returns the server's representation of the cephObjectStoreRealm, and an error, if there is any.
func (c *FakeCephObjectStoreRealms) Create(cephObjectStoreRealm *cephrookiov1.CephObjectStoreRealm) (result *cephrookiov1.CephObjectStoreRealm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cephobjectstorerealmsResource, c.ns, cephObjectStoreRealm), &cephrookiov1.CephObjectStoreRealm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreRealm), err
}

// Update takes the representation of a cephObjectStoreRealm and updates it. Returns the server's representation of the cephObjectStoreRealm, and an error, if there is any.
func (c *FakeCephObjectStoreRealms) Update(cephObjectStoreRealm *cephrookiov1.CephObjectStoreRealm) (result *cephrookiov1.CephObjectStoreRealm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cephobjectstorerealmsResource, c.ns, cephObjectStoreRealm), &cephrookiov1.CephObjectStoreRealm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreRealm), err
}

// Delete takes name of the cephObjectStoreRealm and deletes it. Returns an error if one occurs.
func (c *FakeCephObjectStoreRealms) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cephobjectstorerealmsResource, c.ns, name), &cephrookiov1.CephObjectStoreRealm{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCephObjectStoreRealms) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cephobjectstorerealmsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &cephrookiov1.CephObjectStoreRealmList{})
	return err
}

// Patch applies the patch and returns the patched cephObjectStoreRealm.
func (c *FakeCephObjectStoreRealms) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cephrookiov1.CephObjectStoreRealm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cephobjectstorerealmsResource, c.ns, name, pt, data, subresources...), &cephrookiov1.CephObjectStoreRealm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreRealm), err
}
