/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	cephrookiov1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCephObjectStoreZoneGroups implements CephObjectStoreZoneGroupInterface
type FakeCephObjectStoreZoneGroups struct {
	Fake *FakeCephV1
	ns   string
}

var cephobjectstorezonegroupsResource = schema.GroupVersionResource{Group: "ceph.rook.io", Version: "v1", Resource: "cephobjectstorezonegroups"}

var cephobjectstorezonegroupsKind = schema.GroupVersionKind{Group: "ceph.rook.io", Version: "v1", Kind: "CephObjectStoreZoneGroup"}

// Get takes name of the cephObjectStoreZoneGroup, and returns the corresponding cephObjectStoreZoneGroup object, and an error if there is any.
func (c *FakeCephObjectStoreZoneGroups) Get(name string, options v1.GetOptions) (result *cephrookiov1.CephObjectStoreZoneGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cephobjectstorezonegroupsResource, c.ns, name), &cephrookiov1.CephObjectStoreZoneGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreZoneGroup), err
}

// List takes label and field selectors, and returns the list of CephObjectStoreZoneGroups that match those selectors.
func (c *FakeCephObjectStoreZoneGroups) List(opts v1.ListOptions) (result *cephrookiov1.CephObjectStoreZoneGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cephobjectstorezonegroupsResource, cephobjectstorezonegroupsKind, c.ns, opts), &cephrookiov1.CephObjectStoreZoneGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cephrookiov1.CephObjectStoreZoneGroupList{ListMeta: obj.(*cephrookiov1.CephObjectStoreZoneGroupList).ListMeta}
	for _, item := range obj.(*cephrookiov1.CephObjectStoreZoneGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cephObjectStoreZoneGroups.
func (c *FakeCephObjectStoreZoneGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cephobjectstorezonegroupsResource, c.ns, opts))

}

// Create takes the representation of a cephObjectStoreZoneGroup and creates it.  Returns the server's representation of the cephObjectStoreZoneGroup, and an error, if there is any.
func (c *FakeCephObjectStoreZoneGroups) Create(cephObjectStoreZoneGroup *cephrookiov1.CephObjectStoreZoneGroup) (result *cephrookiov1.CephObjectStoreZoneGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cephobjectstorezonegroupsResource, c.ns, cephObjectStoreZoneGroup), &cephrookiov1.CephObjectStoreZoneGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreZoneGroup), err
}

// Update takes the representation of a cephObjectStoreZoneGroup and updates it. Returns the server's representation of the cephObjectStoreZoneGroup, and an error, if there is any.
func (c *FakeCephObjectStoreZoneGroups) Update(cephObjectStoreZoneGroup *cephrookiov1.CephObjectStoreZoneGroup) (result *cephrookiov1.CephObjectStoreZoneGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cephobjectstorezonegroupsResource, c.ns, cephObjectStoreZoneGroup), &cephrookiov1.CephObjectStoreZoneGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreZoneGroup), err
}

// Delete takes name of the cephObjectStoreZoneGroup and deletes it. Returns an error if one occurs.
func (c *FakeCephObjectStoreZoneGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cephobjectstorezonegroupsResource, c.ns, name), &cephrookiov1.CephObjectStoreZoneGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCephObjectStoreZoneGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cephobjectstorezonegroupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &cephrookiov1.CephObjectStoreZoneGroupList{})
	return err
}

// Patch applies the patch and returns the patched cephObjectStoreZoneGroup.
func (c *FakeCephObjectStoreZoneGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cephrookiov1.CephObjectStoreZoneGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cephobjectstorezonegroupsResource, c.ns, name, pt, data, subresources...), &cephrookiov1.CephObjectStoreZoneGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.CephObjectStoreZoneGroup), err
}
