/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	scheme "github.com/rook/rook/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CephObjectStoreRealmsGetter has a method to return a CephObjectStoreRealmInterface.
// A group's client should implement this interface.
type CephObjectStoreRealmsGetter interface {
	CephObjectStoreRealms(namespace string) CephObjectStoreRealmInterface
}

// CephObjectStoreRealmInterface has methods to work with CephObjectStoreRealm resources.
type CephObjectStoreRealmInterface interface {
	Create(*v1.CephObjectStoreRealm) (*v1.CephObjectStoreRealm, error)
	Update(*v1.CephObjectStoreRealm) (*v1.CephObjectStoreRealm, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CephObjectStoreRealm, error)
	List(opts metav1.ListOptions) (*v1.CephObjectStoreRealmList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CephObjectStoreRealm, err error)
	CephObjectStoreRealmExpansion
}

// cephObjectStoreRealms implements CephObjectStoreRealmInterface
type cephObjectStoreRealms struct {
	client rest.Interface
	ns     string
}

// newCephObjectStoreRealms returns a CephObjectStoreRealms
func newCephObjectStoreRealms(c *CephV1Client, namespace string) *cephObjectStoreRealms {
	return &cephObjectStoreRealms{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cephObjectStoreRealm, and returns the corresponding cephObjectStoreRealm object, and an error if there is any.
func (c *cephObjectStoreRealms) Get(name string, options metav1.GetOptions) (result *v1.CephObjectStoreRealm, err error) {
	result = &v1.CephObjectStoreRealm{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectstorerealms").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CephObjectStoreRealms that match those selectors.
func (c *cephObjectStoreRealms) List(opts metav1.ListOptions) (result *v1.CephObjectStoreRealmList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CephObjectStoreRealmList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectstorerealms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cephObjectStoreRealms.
func (c *cephObjectStoreRealms) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectstorerealms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cephObjectStoreRealm and creates it.  Returns the server's representation of the cephObjectStoreRealm, and an error, if there is any.
func (c *cephObjectStoreRealms) Create(cephObjectStoreRealm *v1.CephObjectStoreRealm) (result *v1.CephObjectStoreRealm, err error) {
	result = &v1.CephObjectStoreRealm{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cephobjectstorerealms").
		Body(cephObjectStoreRealm).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cephObjectStoreRealm and updates it. Returns the server's representation of the cephObjectStoreRealm, and an error, if there is any.
func (c *cephObjectStoreRealms) Update(cephObjectStoreRealm *v1.CephObjectStoreRealm) (result *v1.CephObjectStoreRealm, err error) {
	result = &v1.CephObjectStoreRealm{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cephobjectstorerealms").
		Name(cephObjectStoreRealm.Name).
		Body(cephObjectStoreRealm).
		Do().
		Into(result)
	return
}

// Delete takes name of the cephObjectStoreRealm and deletes it. Returns an error if one occurs.
func (c *cephObjectStoreRealms) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cephobjectstorerealms").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cephObjectStoreRealms) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cephobjectstorerealms").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cephObjectStoreRealm.
func (c *cephObjectStoreRealms) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CephObjectStoreRealm, err error) {
	result = &v1.CephObjectStoreRealm{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cephobjectstorerealms").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
