/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	scheme "github.com/rook/rook/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CephObjectStoreZonesGetter has a method to return a CephObjectStoreZoneInterface.
// A group's client should implement this interface.
type CephObjectStoreZonesGetter interface {
	CephObjectStoreZones(namespace string) CephObjectStoreZoneInterface
}

// CephObjectStoreZoneInterface has methods to work with CephObjectStoreZone resources.
type CephObjectStoreZoneInterface interface {
	Create(*v1.CephObjectStoreZone) (*v1.CephObjectStoreZone, error)
	Update(*v1.CephObjectStoreZone) (*v1.CephObjectStoreZone, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CephObjectStoreZone, error)
	List(opts metav1.ListOptions) (*v1.CephObjectStoreZoneList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CephObjectStoreZone, err error)
	CephObjectStoreZoneExpansion
}

// cephObjectStoreZones implements CephObjectStoreZoneInterface
type cephObjectStoreZones struct {
	client rest.Interface
	ns     string
}

// newCephObjectStoreZones returns a CephObjectStoreZones
func newCephObjectStoreZones(c *CephV1Client, namespace string) *cephObjectStoreZones {
	return &cephObjectStoreZones{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cephObjectStoreZone, and returns the corresponding cephObjectStoreZone object, and an error if there is any.
func (c *cephObjectStoreZones) Get(name string, options metav1.GetOptions) (result *v1.CephObjectStoreZone, err error) {
	result = &v1.CephObjectStoreZone{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectstorezones").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CephObjectStoreZones that match those selectors.
func (c *cephObjectStoreZones) List(opts metav1.ListOptions) (result *v1.CephObjectStoreZoneList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CephObjectStoreZoneList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectstorezones").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cephObjectStoreZones.
func (c *cephObjectStoreZones) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectstorezones").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cephObjectStoreZone and creates it.  Returns the server's representation of the cephObjectStoreZone, and an error, if there is any.
func (c *cephObjectStoreZones) Create(cephObjectStoreZone *v1.CephObjectStoreZone) (result *v1.CephObjectStoreZone, err error) {
	result = &v1.CephObjectStoreZone{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cephobjectstorezones").
		Body(cephObjectStoreZone).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cephObjectStoreZone and updates it. Returns the server's representation of the cephObjectStoreZone, and an error, if there is any.
func (c *cephObjectStoreZones) Update(cephObjectStoreZone *v1.CephObjectStoreZone) (result *v1.CephObjectStoreZone, err error) {
	result = &v1.CephObjectStoreZone{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cephobjectstorezones").
		Name(cephObjectStoreZone.Name).
		Body(cephObjectStoreZone).
		Do().
		Into(result)
	return
}

// Delete takes name of the cephObjectStoreZone and deletes it. Returns an error if one occurs.
func (c *cephObjectStoreZones) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cephobjectstorezones").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cephObjectStoreZones) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cephobjectstorezones").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cephObjectStoreZone.
func (c *cephObjectStoreZones) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CephObjectStoreZone, err error) {
	result = &v1.CephObjectStoreZone{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cephobjectstorezones").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
