/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	scheme "github.com/rook/rook/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CephObjectStoreZoneGroupsGetter has a method to return a CephObjectStoreZoneGroupInterface.
// A group's client should implement this interface.
type CephObjectStoreZoneGroupsGetter interface {
	CephObjectStoreZoneGroups(namespace string) CephObjectStoreZoneGroupInterface
}

// CephObjectStoreZoneGroupInterface has methods to work with CephObjectStoreZoneGroup resources.
type CephObjectStoreZoneGroupInterface interface {
	Create(*v1.CephObjectStoreZoneGroup) (*v1.CephObjectStoreZoneGroup, error)
	Update(*v1.CephObjectStoreZoneGroup) (*v1.CephObjectStoreZoneGroup, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CephObjectStoreZoneGroup, error)
	List(opts metav1.ListOptions) (*v1.CephObjectStoreZoneGroupList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CephObjectStoreZoneGroup, err error)
	CephObjectStoreZoneGroupExpansion
}

// cephObjectStoreZoneGroups implements CephObjectStoreZoneGroupInterface
type cephObjectStoreZoneGroups struct {
	client rest.Interface
	ns     string
}

// newCephObjectStoreZoneGroups returns a CephObjectStoreZoneGroups
func newCephObjectStoreZoneGroups(c *CephV1Client, namespace string) *cephObjectStoreZoneGroups {
	return &cephObjectStoreZoneGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cephObjectStoreZoneGroup, and returns the corresponding cephObjectStoreZoneGroup object, and an error if there is any.
func (c *cephObjectStoreZoneGroups) Get(name string, options metav1.GetOptions) (result *v1.CephObjectStoreZoneGroup, err error) {
	result = &v1.CephObjectStoreZoneGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectstorezonegroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CephObjectStoreZoneGroups that match those selectors.
func (c *cephObjectStoreZoneGroups) List(opts metav1.ListOptions) (result *v1.CephObjectStoreZoneGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CephObjectStoreZoneGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectstorezonegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cephObjectStoreZoneGroups.
func (c *cephObjectStoreZoneGroups) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectstorezonegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cephObjectStoreZoneGroup and creates it.  Returns the server's representation of the cephObjectStoreZoneGroup, and an error, if there is any.
func (c *cephObjectStoreZoneGroups) Create(cephObjectStoreZoneGroup *v1.CephObjectStoreZoneGroup) (result *v1.CephObjectStoreZoneGroup, err error) {
	result = &v1.CephObjectStoreZoneGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cephobjectstorezonegroups").
		Body(cephObjectStoreZoneGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cephObjectStoreZoneGroup and updates it. Returns the server's representation of the cephObjectStoreZoneGroup, and an error, if there is any.
func (c *cephObjectStoreZoneGroups) Update(cephObjectStoreZoneGroup *v1.CephObjectStoreZoneGroup) (result *v1.CephObjectStoreZoneGroup, err error) {
	result = &v1.CephObjectStoreZoneGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cephobjectstorezonegroups").
		Name(cephObjectStoreZoneGroup.Name).
		Body(cephObjectStoreZoneGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the cephObjectStoreZoneGroup and deletes it. Returns an error if one occurs.
func (c *cephObjectStoreZoneGroups) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cephobjectstorezonegroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cephObjectStoreZoneGroups) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cephobjectstorezonegroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cephObjectStoreZoneGroup.
func (c *cephObjectStoreZoneGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CephObjectStoreZoneGroup, err error) {
	result = &v1.CephObjectStoreZoneGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cephobjectstorezonegroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
